repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.7
    hooks:
      # Run the formatters.
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      - id: ruff-format
