name: npanalyst
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - joblib
  - numpy
  - pandas
  - scipy
  - click
  - networkx=2.6
  - scikit-learn
  - matplotlib-base
  - python-louvain
  - pygraphviz
  - pip:
      - rtree
      - pymzml==2.4.5
